spring.application.name=tienda-ropa
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:tiendadb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JWT and Security Settings
security.jwt.secret-key=${JWT_SECRET_KEY:NDA0RTYzNTI2NjU1NkE1ODZOMzI3MjM1NzUzODd4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME:86400000}
security.admin-passcode=${ADMIN_PASSCODE:URBANWEAR-SECRET-ADMIN-2026}
